name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1"
          cache: true
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
